name: Publishing To NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 12
        uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.name "muhammadrafeh"
      - run: git config --global user.email "muhammadrafehatique@gmail.com"

      - run: npm version patch
      
      - run: npm install

      - run: npm pack

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git push origin HEAD:main
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}